"""Seed the database with fake data for local development.

All person data is generated by Faker. Zero PII.
Uses Faker.seed(0) for deterministic output — same fake names every run.
"""

from __future__ import annotations

from datetime import date, timedelta
from decimal import Decimal
from typing import Any

from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.core.management.base import BaseCommand
from faker import Faker

from membership.models import (
    Guild,
    GuildVote,
    Lease,
    Member,
    MembershipPlan,
    Space,
)

User = get_user_model()
fake = Faker()

ADMIN_EMAIL = "admin@pastlives.space"

GUILD_DEFINITIONS: list[dict[str, str]] = [
    {"name": "Woodworking"},
    {"name": "Metalworking"},
    {"name": "Ceramics"},
    {"name": "Textiles & Fiber Arts"},
    {"name": "Electronics"},
    {"name": "3D Printing & CNC"},
    {"name": "Screen Printing"},
    {"name": "Photography"},
    {"name": "Jewelry"},
    {"name": "Leatherworking"},
    {"name": "Glass Arts"},
    {"name": "Prison Outreach"},
    {"name": "Bicycle Workshop"},
    {"name": "Community Kitchen"},
]

SPACE_DEFINITIONS: list[dict[str, Any]] = [
    {
        "space_id": "STU-101",
        "name": "Studio A",
        "space_type": "studio",
        "size_sqft": Decimal("200.00"),
        "rate_per_sqft": Decimal("3.75"),
        "status": "occupied",
    },
    {
        "space_id": "STU-102",
        "name": "Studio B",
        "space_type": "studio",
        "size_sqft": Decimal("150.00"),
        "rate_per_sqft": Decimal("3.75"),
        "status": "occupied",
    },
    {
        "space_id": "STO-201",
        "name": "Storage Unit 1",
        "space_type": "storage",
        "size_sqft": Decimal("50.00"),
        "rate_per_sqft": Decimal("3.75"),
        "status": "occupied",
    },
    {
        "space_id": "DSK-301",
        "name": "Hot Desk 1",
        "space_type": "desk",
        "manual_price": Decimal("100.00"),
        "status": "available",
    },
]

# Guild lead assignments: index into members list (0-14 are guild leads)
# 14 guilds, 15 leads => Prison Outreach gets 2 (indices 11 and 14)
GUILD_LEAD_INDICES: list[list[int]] = [
    [0],  # Woodworking
    [1],  # Metalworking
    [2],  # Ceramics
    [3],  # Textiles & Fiber Arts
    [4],  # Electronics
    [5],  # 3D Printing & CNC
    [6],  # Screen Printing
    [7],  # Photography
    [8],  # Jewelry
    [9],  # Leatherworking
    [10],  # Glass Arts
    [11, 14],  # Prison Outreach (2 co-leads)
    [12],  # Bicycle Workshop
    [13],  # Community Kitchen
]

PLAN_DEFINITIONS: list[dict[str, Any]] = [
    {"name": "Standard", "monthly_price": Decimal("150.00"), "deposit_required": Decimal("150.00")},
    {"name": "Work-Trade", "monthly_price": Decimal("75.00"), "deposit_required": Decimal("75.00")},
    {"name": "Day Pass", "monthly_price": Decimal("25.00")},
]


class Command(BaseCommand):
    help = "Seed database with fake data for local development. All person data generated by Faker."

    def add_arguments(self, parser: Any) -> None:
        parser.add_argument(
            "--flush",
            action="store_true",
            help="Delete all existing seed data and recreate from scratch.",
        )

    def handle(self, *args: Any, **options: Any) -> None:
        flush = options["flush"]

        if not flush and Member.objects.exists():
            self.stdout.write(self.style.WARNING("Data already exists. Use --flush to recreate."))
            return

        if flush:
            self._flush()

        Faker.seed(0)
        self._seed()
        self.stdout.write(self.style.SUCCESS("Seed data created successfully."))

    def _flush(self) -> None:
        """Delete all seed data, preserving the admin superuser."""
        self.stdout.write("Flushing existing data...")
        GuildVote.objects.all().delete()
        Lease.objects.all().delete()
        Member.objects.all().delete()
        Guild.objects.all().delete()
        Space.objects.all().delete()
        MembershipPlan.objects.all().delete()
        # Delete all non-admin users
        User.objects.exclude(email=ADMIN_EMAIL).delete()

    def _seed(self) -> None:
        """Create all seed data."""
        self._create_admin()
        plans = self._create_plans()
        guilds = self._create_guilds()
        members = self._create_members(plans)
        self._assign_guild_leads(guilds, members)
        spaces = self._create_spaces()
        self._create_leases(members, spaces)
        self._create_guild_votes(guilds, members)

    def _create_admin(self) -> Any:
        user, created = User.objects.get_or_create(
            email=ADMIN_EMAIL,
            defaults={
                "username": "admin",
                "is_staff": True,
                "is_superuser": True,
            },
        )
        if created:
            user.set_password("admin")
            user.save()
        return user

    def _create_plans(self) -> list[MembershipPlan]:
        plans = []
        for defn in PLAN_DEFINITIONS:
            plan, _ = MembershipPlan.objects.get_or_create(
                name=defn["name"],
                defaults={k: v for k, v in defn.items() if k != "name"},
            )
            plans.append(plan)
        return plans

    def _create_guilds(self) -> list[Guild]:
        guilds = []
        for defn in GUILD_DEFINITIONS:
            guild, _ = Guild.objects.get_or_create(name=defn["name"])
            guilds.append(guild)
        return guilds

    def _create_members(self, plans: list[MembershipPlan]) -> list[Member]:
        """Create 30 members: 7 staff, 15 guild leads, 8 regular."""
        members: list[Member] = []
        standard_plan = plans[0]  # Standard
        work_trade_plan = plans[1]  # Work-Trade

        for i in range(30):
            first = fake.first_name()
            last = fake.last_name()
            full_name = f"{first} {last}"
            email = f"{first.lower()}.{last.lower()}@example.com"
            username = f"{first.lower()}{last.lower()}{i}"
            preferred = first if fake.boolean(chance_of_getting_true=40) else ""

            is_staff = i < 7
            is_guild_lead = 7 <= i < 22
            plan = work_trade_plan if is_staff else standard_plan
            role = (
                Member.Role.EMPLOYEE if is_staff else Member.Role.GUILD_LEAD if is_guild_lead else Member.Role.STANDARD
            )

            user = User.objects.create_user(
                username=username,
                email=email,
                password="testpass123",
                is_staff=is_staff,
            )

            member = Member.objects.create(
                user=user,
                full_legal_name=full_name,
                preferred_name=preferred,
                email=email,
                phone=fake.phone_number(),
                membership_plan=plan,
                status=Member.Status.ACTIVE,
                role=role,
                join_date=date(2024, 1, 1) + timedelta(days=i * 10),
                emergency_contact_name=fake.name(),
                emergency_contact_phone=fake.phone_number(),
                emergency_contact_relationship=fake.random_element(["Partner", "Parent", "Sibling", "Friend"]),
            )
            members.append(member)

        return members

    def _assign_guild_leads(self, guilds: list[Guild], members: list[Member]) -> None:
        """Assign guild leads (members 7-21) to guilds."""
        lead_members = members[7:22]  # 15 guild leads

        for guild, lead_indices in zip(guilds, GUILD_LEAD_INDICES):
            primary_lead_idx = lead_indices[0]
            guild.guild_lead = lead_members[primary_lead_idx]
            guild.save()

    def _create_spaces(self) -> list[Space]:
        spaces = []
        for defn in SPACE_DEFINITIONS:
            space, _ = Space.objects.get_or_create(
                space_id=defn["space_id"],
                defaults={k: v for k, v in defn.items() if k != "space_id"},
            )
            spaces.append(space)
        return spaces

    def _create_leases(self, members: list[Member], spaces: list[Space]) -> None:
        """Create 3 leases: first 3 members get first 3 spaces."""
        member_ct = ContentType.objects.get_for_model(Member)
        today = date.today()

        for i in range(3):
            Lease.objects.get_or_create(
                content_type=member_ct,
                object_id=members[i].pk,
                space=spaces[i],
                defaults={
                    "lease_type": Lease.LeaseType.MONTH_TO_MONTH,
                    "base_price": spaces[i].full_price or Decimal("200.00"),
                    "monthly_rent": spaces[i].full_price or Decimal("200.00"),
                    "start_date": today - timedelta(days=90),
                },
            )

    def _create_guild_votes(self, guilds: list[Guild], members: list[Member]) -> None:
        """Create sample guild votes: each regular member votes for 3 guilds."""
        regular_members = members[22:]  # 8 regular members
        for member in regular_members:
            chosen = fake.random_elements(guilds, length=3, unique=True)
            for priority, guild in enumerate(chosen, start=1):
                GuildVote.objects.get_or_create(
                    member=member,
                    guild=guild,
                    defaults={"priority": priority},
                )
