# Generated by Django 6.0.3 on 2026-04-02 05:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("membership", "0018_alter_memberemail_member"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "charge_frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly"), ("off", "Off")],
                        default="monthly",
                        help_text="How often to run the billing cycle.",
                        max_length=20,
                    ),
                ),
                (
                    "charge_time",
                    models.TimeField(default="23:00", help_text="Time of day to run billing (Pacific time)."),
                ),
                (
                    "charge_day_of_week",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Day of week for WEEKLY billing (0=Monday .. 6=Sunday).", null=True
                    ),
                ),
                (
                    "charge_day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Day of month for MONTHLY billing (1-28).", null=True
                    ),
                ),
                (
                    "default_tab_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("200.00"),
                        help_text="Maximum tab balance before new entries are blocked.",
                        max_digits=8,
                    ),
                ),
                (
                    "max_retry_attempts",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="Number of times to retry a failed charge before locking the tab."
                    ),
                ),
                (
                    "retry_interval_hours",
                    models.PositiveSmallIntegerField(
                        default=24, help_text="Hours between retry attempts for failed charges."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last time billing settings were changed."),
                ),
            ],
            options={
                "verbose_name": "Billing Settings",
                "verbose_name_plural": "Billing Settings",
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("pk", 1)), name="billing_settings_singleton"),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("charge_frequency", "weekly"), ("charge_day_of_week__isnull", True), _connector="OR"
                        ),
                        name="billing_settings_day_of_week_only_weekly",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("charge_frequency", "monthly"), ("charge_day_of_month__isnull", True), _connector="OR"
                        ),
                        name="billing_settings_day_of_month_only_monthly",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("charge_day_of_week__isnull", True), ("charge_day_of_week__lte", 6), _connector="OR"
                        ),
                        name="billing_settings_day_of_week_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("charge_day_of_month__isnull", True),
                            models.Q(("charge_day_of_month__gte", 1), ("charge_day_of_month__lte", 28)),
                            _connector="OR",
                        ),
                        name="billing_settings_day_of_month_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Tab",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, help_text="Stripe Customer ID for this member.", max_length=255),
                ),
                (
                    "stripe_payment_method_id",
                    models.CharField(blank=True, help_text="Default Stripe PaymentMethod ID on file.", max_length=255),
                ),
                (
                    "payment_method_last4",
                    models.CharField(
                        blank=True, help_text="Last 4 digits of the payment method on file.", max_length=4
                    ),
                ),
                (
                    "payment_method_brand",
                    models.CharField(blank=True, help_text="Card brand (e.g. visa, mastercard).", max_length=20),
                ),
                (
                    "tab_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Per-member tab limit override. Null means use the default from BillingSettings.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked tabs cannot accept new entries (usually due to failed payment).",
                    ),
                ),
                ("locked_reason", models.CharField(blank=True, help_text="Why this tab is locked.", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When this tab was created.")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Last time this tab was modified.")),
                (
                    "member",
                    models.OneToOneField(
                        help_text="The member this tab belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tab",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tab",
                "verbose_name_plural": "Tabs",
            },
        ),
        migrations.CreateModel(
            name="TabCharge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the charge.",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, help_text="Total amount charged in USD.", max_digits=8),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, help_text="Stripe PaymentIntent ID.", max_length=255),
                ),
                ("stripe_charge_id", models.CharField(blank=True, help_text="Stripe Charge ID.", max_length=255)),
                ("stripe_receipt_url", models.URLField(blank=True, help_text="Link to Stripe-hosted receipt.")),
                (
                    "failure_reason",
                    models.TextField(blank=True, help_text="Error message from Stripe if the charge failed."),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(default=0, help_text="Number of retry attempts so far."),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(blank=True, help_text="When to attempt the next retry.", null=True),
                ),
                (
                    "receipt_sent_at",
                    models.DateTimeField(blank=True, help_text="When the receipt email was sent.", null=True),
                ),
                (
                    "charged_at",
                    models.DateTimeField(blank=True, help_text="When the charge was confirmed successful.", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this charge record was created."),
                ),
                (
                    "tab",
                    models.ForeignKey(
                        help_text="The tab this charge belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="billing.tab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tab Charge",
                "verbose_name_plural": "Tab Charges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TabEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(help_text="What this charge is for.", max_length=500)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, help_text="Amount in USD. Must be positive.", max_digits=8),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("manual", "Manual")], default="manual", help_text="Type of charge.", max_length=20
                    ),
                ),
                (
                    "is_self_service",
                    models.BooleanField(default=False, help_text="Whether the member added this themselves."),
                ),
                (
                    "voided_at",
                    models.DateTimeField(
                        blank=True, help_text="When this entry was voided. Null means active.", null=True
                    ),
                ),
                ("voided_reason", models.CharField(blank=True, help_text="Why this entry was voided.", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When this entry was created.")),
                ("notes", models.TextField(blank=True, help_text="Internal notes about this entry.")),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who added this entry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tab_entries_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tab",
                    models.ForeignKey(
                        help_text="The tab this entry belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="billing.tab",
                    ),
                ),
                (
                    "tab_charge",
                    models.ForeignKey(
                        blank=True,
                        help_text="The charge this entry was billed in. Null means pending.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="billing.tabcharge",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who voided this entry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tab_entries_voided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tab Entry",
                "verbose_name_plural": "Tab Entries",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="tab_entry_amount_positive")
                ],
            },
        ),
    ]
