# Generated by Django 6.0.3 on 2026-04-02 18:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        ("membership", "0018_alter_memberemail_member"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tabcharge",
            name="application_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Platform application fee collected on this charge.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Display name of the product.", max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, help_text="Price in USD. Must be positive.", max_digits=8),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this product is currently available."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When this product was created.")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this product.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        help_text="The guild that offers this product.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["guild__name", "name"],
            },
        ),
        migrations.AddField(
            model_name="tabentry",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="The product this entry is for, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tab_entries",
                to="billing.product",
            ),
        ),
        migrations.CreateModel(
            name="StripeAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stripe_account_id",
                    models.CharField(help_text="Stripe Connect account ID (acct_xxx).", max_length=255),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Human-readable name for this Stripe account.", max_length=255),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this Stripe account is currently active."),
                ),
                (
                    "platform_fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of each charge kept by the platform (0-100).",
                        max_digits=5,
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(blank=True, help_text="When this Stripe account was connected.", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When this record was created.")),
                (
                    "guild",
                    models.OneToOneField(
                        blank=True,
                        help_text="The guild this Stripe account belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stripe_account",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stripe Account",
                "verbose_name_plural": "Stripe Accounts",
            },
        ),
        migrations.AddField(
            model_name="tabcharge",
            name="stripe_account",
            field=models.ForeignKey(
                blank=True,
                help_text="The Stripe Connect account this charge was sent to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charges",
                to="billing.stripeaccount",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(condition=models.Q(("price__gt", 0)), name="product_price_positive"),
        ),
    ]
