# Generated by Django 6.0.3 on 2026-04-07 19:57

import billing.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_tabcharge_application_fee_product_tabentry_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeaccount",
            name="auth_mode",
            field=models.CharField(
                choices=[("oauth", "Stripe Connect (OAuth)"), ("direct_keys", "Direct API Keys")],
                default="oauth",
                help_text="How this guild's Stripe account is authenticated.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stripeaccount",
            name="direct_publishable_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Guild's Stripe publishable key (pk_…). Sent to the browser.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="stripeaccount",
            name="direct_secret_key",
            field=billing.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="Guild's Stripe secret key (sk_test_… or sk_live_…). Encrypted at rest.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="stripeaccount",
            name="direct_webhook_secret",
            field=billing.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="Webhook signing secret from this guild's Stripe dashboard. Encrypted at rest.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="tabcharge",
            name="stripe_checkout_session_id",
            field=models.CharField(
                blank=True, help_text="Stripe Checkout Session ID (direct-keys mode only).", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="tabcharge",
            name="stripe_checkout_url",
            field=models.URLField(
                blank=True, help_text="Hosted Checkout URL the member opens to pay (direct-keys mode only)."
            ),
        ),
        migrations.AlterField(
            model_name="stripeaccount",
            name="stripe_account_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe account ID (acct_xxx). Set by OAuth or by verifying direct keys.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="tabcharge",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("pending_checkout", "Awaiting member checkout"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Current status of the charge.",
                max_length=20,
            ),
        ),
    ]
