# Generated by Django 6.0.3 on 2026-04-07 21:31

import billing.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_stripeaccount_auth_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingsettings",
            name="connect_client_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe Connect application client ID (ca_…). From dashboard.stripe.com/settings/connect.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="connect_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Master switch for Stripe Connect platform billing. When off, the OAuth tab is hidden.",
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="connect_platform_publishable_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="PL platform Stripe publishable key (pk_…). Sent to the browser for the payment-method setup flow.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="connect_platform_secret_key",
            field=billing.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="PL platform Stripe secret key (sk_…). Used for OAuth Connect destination charges. Encrypted at rest.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="billingsettings",
            name="connect_platform_webhook_secret",
            field=billing.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="Webhook signing secret for the global /billing/webhooks/stripe/ endpoint. Encrypted at rest.",
                max_length=512,
            ),
        ),
    ]
