# Generated by Django 6.0.2 on 2026-04-12 02:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_billingsettings_connect_client_id_and_more"),
        ("membership", "0023_fundingsnapshot_minimum_pool_raw_votes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billingsettings",
            name="default_admin_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20.00"),
                help_text="Site-wide default admin percentage on each charge (0-100). Overridden per-product on Product.admin_percent_override.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="admin_percent_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Admin percent for this product (0-100). Overrides BillingSettings.default_admin_percent when set. Null uses the site default.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="split_mode",
            field=models.CharField(
                choices=[
                    ("single_guild", "Guild share to owning guild"),
                    ("split_equally", "Guild share split equally across all active guilds"),
                ],
                default="single_guild",
                help_text="How the guild portion of this product's charges is allocated.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tabentry",
            name="admin_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Admin percentage applied to this entry at the time it was created. Guild share = amount * (1 - admin_percent/100).",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tabentry",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning guild for this entry, snapshotted at creation time. Null for manual/unattributed entries.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tab_entries",
                to="membership.guild",
            ),
        ),
        migrations.AddField(
            model_name="tabentry",
            name="split_guild_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Snapshot of active guild IDs at entry creation, used for SPLIT_EQUALLY entries. Empty list for SINGLE_GUILD entries.",
            ),
        ),
        migrations.AddField(
            model_name="tabentry",
            name="split_mode",
            field=models.CharField(
                choices=[
                    ("single_guild", "Guild share to owning guild"),
                    ("split_equally", "Guild share split equally across all active guilds"),
                ],
                default="single_guild",
                help_text="How the guild portion of this entry is allocated among guilds.",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="billingsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("default_admin_percent__gte", 0), ("default_admin_percent__lte", 100)),
                name="billing_settings_default_admin_percent_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("admin_percent_override__isnull", True),
                    models.Q(("admin_percent_override__gte", 0), ("admin_percent_override__lte", 100)),
                    _connector="OR",
                ),
                name="product_admin_percent_override_range",
            ),
        ),
    ]
