# Generated by Django 6.0.3 on 2026-04-14 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0008_drop_stripe_account"),
        ("membership", "0023_fundingsnapshot_minimum_pool_raw_votes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRevenueSplit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[("admin", "Admin"), ("guild", "Guild")],
                        help_text="Whether this row pays the admin or a specific guild.",
                        max_length=10,
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of the product price this recipient receives. 0 < percent <= 100.",
                        max_digits=5,
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        help_text="The guild this row pays. Required for GUILD rows, must be NULL for ADMIN rows.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_revenue_splits",
                        to="membership.guild",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product this split row belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="billing.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Revenue Split",
                "verbose_name_plural": "Product Revenue Splits",
                "ordering": ["product_id", "recipient_type", "guild_id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("percent__gt", 0), ("percent__lte", 100)), name="prodrevsplit_percent_range"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("recipient_type", "guild"), ("guild__isnull", False)),
                            models.Q(("recipient_type", "admin"), ("guild__isnull", True)),
                            _connector="OR",
                        ),
                        name="prodrevsplit_recipient_guild_consistent",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("recipient_type", "admin")),
                        fields=("product",),
                        name="uq_prodrevsplit_admin_per_product",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("recipient_type", "guild")),
                        fields=("product", "guild"),
                        name="uq_prodrevsplit_guild_per_product",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TabEntrySplit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[("admin", "Admin"), ("guild", "Guild")],
                        help_text="Whether this row paid the admin or a specific guild.",
                        max_length=10,
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of the entry amount paid to this recipient at snapshot time.",
                        max_digits=5,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Dollar amount paid to this recipient. Computed at snapshot time.",
                        max_digits=8,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        help_text="The tab entry this split row belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="billing.tabentry",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        help_text="The guild this row paid (snapshot). Required for GUILD rows, NULL for ADMIN rows.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tab_entry_splits",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tab Entry Split",
                "verbose_name_plural": "Tab Entry Splits",
                "ordering": ["entry_id", "recipient_type", "guild_id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("percent__gt", 0), ("percent__lte", 100)),
                        name="tabentrysplit_percent_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("recipient_type", "guild"), ("guild__isnull", False)),
                            models.Q(("recipient_type", "admin"), ("guild__isnull", True)),
                            _connector="OR",
                        ),
                        name="tabentrysplit_recipient_guild_consistent",
                    ),
                ],
            },
        ),
    ]
