# Generated by Django 6.0.4 on 2026-04-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_revenuesplit_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', help_text='What this product is. Shown to members on the guild page.'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional product image.', null=True, upload_to='products/'),
        ),
    ]
