services:
  web:
    build: .
    ports:
      - "8008:8008"
    volumes:
      - .:/app
    env_file: .env
    command: >
      sh -c "pip install -r requirements-dev.txt &&
             python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8008"
