# Generated by Django 6.0.3 on 2026-04-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_publicly', models.BooleanField(default=False, help_text='When False, /classes/ public routes return 404. Admin + instructor dashboards stay available.')),
                ('liability_waiver_text', models.TextField(help_text='Full liability waiver text shown to all registrants.')),
                ('model_release_waiver_text', models.TextField(help_text='Full model-release waiver text shown when a class requires it.')),
                ('default_member_discount_pct', models.PositiveIntegerField(default=10, help_text='Percent discount auto-applied to registrations from verified Members (0 = no discount).')),
                ('reminder_hours_before', models.PositiveIntegerField(default=24, help_text='Hours before a class session to send the reminder email.')),
                ('instructor_approval_required', models.BooleanField(default=True, help_text='When on, new classes go to admin for review before being published.')),
                ('mailchimp_api_key', models.CharField(blank=True, help_text='MailChimp API key for auto-subscribe.', max_length=255)),
                ('mailchimp_list_id', models.CharField(blank=True, help_text='MailChimp list ID for class registrants.', max_length=255)),
                ('google_analytics_measurement_id', models.CharField(blank=True, help_text='GA4 measurement ID (e.g. G-XXXXXXX). Leave blank to disable GA tag.', max_length=50)),
                ('confirmation_email_footer', models.TextField(blank=True, help_text='Custom footer appended to confirmation emails.')),
            ],
            options={
                'verbose_name': 'Class Settings',
                'verbose_name_plural': 'Class Settings',
            },
        ),
    ]
