# Generated by Django 6.0.3 on 2026-04-20 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0002_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(help_text="Public name shown on class pages.", max_length=255)),
                ("slug", models.SlugField(help_text="URL slug for public profile.", max_length=255, unique=True)),
                ("bio", models.TextField(blank=True, help_text="Markdown-safe bio shown on profile.")),
                ("photo", models.ImageField(blank=True, help_text="Profile photo.", upload_to="classes/instructors/")),
                ("website", models.URLField(blank=True, help_text="Personal site.")),
                (
                    "social_handle",
                    models.CharField(blank=True, help_text="e.g. @handle on primary social.", max_length=255),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Inactive instructors hidden from public browse."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Auth identity — required.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
    ]
