# Generated by Django 6.0.3 on 2026-04-20 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Public class title.', max_length=255)),
                ('slug', models.SlugField(help_text='URL slug.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Class description — markdown-safe.')),
                ('prerequisites', models.TextField(blank=True, help_text='What a student should know/own.')),
                ('materials_included', models.TextField(blank=True, help_text='Included materials.')),
                ('materials_to_bring', models.TextField(blank=True, help_text='What students must bring.')),
                ('safety_requirements', models.TextField(blank=True, help_text='PPE or other safety requirements.')),
                ('age_minimum', models.PositiveIntegerField(blank=True, help_text='Minimum age.', null=True)),
                ('age_guardian_note', models.TextField(blank=True, help_text='Notes about minors / guardians.')),
                ('price_cents', models.PositiveIntegerField(help_text='Full price in cents.')),
                ('member_discount_pct', models.PositiveIntegerField(default=10, help_text='Auto-applied for verified members.')),
                ('capacity', models.PositiveIntegerField(default=6, help_text='Maximum confirmed registrants.')),
                ('scheduling_model', models.CharField(choices=[('fixed', 'Fixed sessions'), ('flexible', 'Flexible (arrange with instructor)')], default='fixed', help_text='Fixed scheduled sessions or flexible per-student scheduling.', max_length=10)),
                ('flexible_note', models.TextField(blank=True, help_text='Notes when scheduling_model=flexible.')),
                ('is_private', models.BooleanField(default=False, help_text='Hidden from public portal; private registration only.')),
                ('private_for_name', models.CharField(blank=True, help_text='Name shown when private.', max_length=255)),
                ('recurring_pattern', models.CharField(blank=True, help_text='Free-text recurrence description.', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Hero image.', upload_to='classes/images/')),
                ('requires_model_release', models.BooleanField(default=False, help_text='When on, registrants also sign model release.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Lifecycle status.', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='Stamp on first publish.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin user who approved publication.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Category grouping.', on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='classes.category')),
                ('created_by', models.ForeignKey(blank=True, help_text='Instructor who authored the class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='classes.instructor')),
                ('instructor', models.ForeignKey(help_text='Assigned instructor.', on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='classes.instructor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
