# Generated by Django 6.0.3 on 2026-04-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_classsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Uppercase code — normalized on save.', max_length=40, unique=True)),
                ('description', models.CharField(blank=True, help_text='Admin-only description.', max_length=255)),
                ('discount_pct', models.PositiveIntegerField(blank=True, help_text='Percent off (0-100).', null=True)),
                ('discount_fixed_cents', models.PositiveIntegerField(blank=True, help_text='Flat cents off.', null=True)),
                ('valid_from', models.DateField(blank=True, help_text='First date the code is valid.', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Last date the code is valid.', null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Cap total uses. Null = unlimited.', null=True)),
                ('use_count', models.PositiveIntegerField(default=0, help_text='Incremented on each successful registration.')),
                ('is_active', models.BooleanField(default=True, help_text='Admin toggle to disable without deleting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_pct__isnull', False), ('discount_fixed_cents__isnull', False), _connector='OR'), name='discount_has_value')],
            },
        ),
    ]
