# Generated by Django 6.0.3 on 2026-04-20 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0006_discountcode"),
        ("membership", "0027_calendarevent_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(help_text="Registrant first name.", max_length=100)),
                ("last_name", models.CharField(help_text="Registrant last name.", max_length=100)),
                ("pronouns", models.CharField(blank=True, help_text="Optional pronouns.", max_length=50)),
                (
                    "email",
                    models.EmailField(
                        help_text="Registrant email — drives member linking + self-serve link.", max_length=254
                    ),
                ),
                ("phone", models.CharField(blank=True, help_text="Optional phone.", max_length=20)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_city", models.CharField(blank=True, max_length=100)),
                ("address_state", models.CharField(blank=True, max_length=50)),
                ("address_zip", models.CharField(blank=True, max_length=20)),
                ("prior_experience", models.TextField(blank=True, help_text="Free-text prior-experience question.")),
                (
                    "looking_for",
                    models.TextField(
                        blank=True, help_text="Free-text 'what are you hoping to get out of this?' question."
                    ),
                ),
                (
                    "amount_paid_cents",
                    models.PositiveIntegerField(default=0, help_text="Amount actually paid (after discount)."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending payment"),
                            ("confirmed", "Confirmed"),
                            ("waitlisted", "Waitlisted"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        help_text="Lifecycle status.",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(blank=True, help_text="Stripe Checkout Session ID.", max_length=255),
                ),
                (
                    "stripe_payment_id",
                    models.CharField(blank=True, help_text="Stripe PaymentIntent ID on confirm.", max_length=255),
                ),
                (
                    "self_serve_token",
                    models.CharField(
                        db_index=True,
                        help_text="Random token used in /classes/my/<token>/ self-serve URL.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "subscribed_to_mailchimp",
                    models.BooleanField(default=False, help_text="Whether MailChimp subscribe succeeded."),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "class_offering",
                    models.ForeignKey(
                        help_text="The class this registration is for.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="classes.classoffering",
                    ),
                ),
                (
                    "discount_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="Discount code used at registration, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="classes.discountcode",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Auto-linked when email matches a verified Member email.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_registrations",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registration",
                    models.ForeignKey(
                        help_text="The registration the reminder was sent to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="classes.registration",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="The session the reminder referenced.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="classes.classsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="Waiver",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("liability", "Liability"), ("model_release", "Model Release")],
                        help_text="Which waiver was signed.",
                        max_length=20,
                    ),
                ),
                ("waiver_text", models.TextField(help_text="Full text as shown at time of signing (audit record).")),
                ("signature_text", models.CharField(help_text="Name typed as signature.", max_length=255)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, help_text="Client IP at time of signing.", null=True),
                ),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registration",
                    models.ForeignKey(
                        help_text="The registration this waiver belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waivers",
                        to="classes.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["-signed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(fields=["email"], name="classes_reg_email_34da35_idx"),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(fields=["class_offering", "status"], name="classes_reg_class_o_d23234_idx"),
        ),
        migrations.AddConstraint(
            model_name="registrationreminder",
            constraint=models.UniqueConstraint(
                fields=("registration", "session"), name="uq_reminder_registration_session"
            ),
        ),
        migrations.AddConstraint(
            model_name="waiver",
            constraint=models.UniqueConstraint(fields=("registration", "kind"), name="uq_waiver_registration_kind"),
        ),
    ]
