# Generated by Django 6.0.3 on 2026-04-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0008_seed_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="cancellation_reason",
            field=models.TextField(blank=True, help_text="Internal reason recorded when an admin cancels."),
        ),
        migrations.AlterField(
            model_name="registration",
            name="address_city",
            field=models.CharField(blank=True, help_text="City (optional).", max_length=100),
        ),
        migrations.AlterField(
            model_name="registration",
            name="address_line1",
            field=models.CharField(blank=True, help_text="Street address (optional).", max_length=255),
        ),
        migrations.AlterField(
            model_name="registration",
            name="address_state",
            field=models.CharField(blank=True, help_text="State or region (optional).", max_length=50),
        ),
        migrations.AlterField(
            model_name="registration",
            name="address_zip",
            field=models.CharField(blank=True, help_text="Postal / ZIP code (optional).", max_length=20),
        ),
        migrations.AlterField(
            model_name="registration",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, help_text="When this registration was cancelled.", null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, help_text="When payment confirmed, if any.", null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="registered_at",
            field=models.DateTimeField(auto_now_add=True, help_text="When this registration was created."),
        ),
    ]
