# Generated by Django 6.0.3 on 2026-04-22 05:47

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0009_registration_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional header image.",
                upload_to="classes/categories/",
                validators=[core.validators.validate_image_size],
            ),
        ),
        migrations.AlterField(
            model_name="classoffering",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Hero image.",
                upload_to="classes/images/",
                validators=[core.validators.validate_image_size],
            ),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Profile photo.",
                upload_to="classes/instructors/",
                validators=[core.validators.validate_image_size],
            ),
        ),
    ]
