# Generated by Django 6.0.3 on 2026-04-23 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0012_copy_mailchimp_ga_to_site_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classsettings",
            name="google_analytics_measurement_id",
        ),
        migrations.RemoveField(
            model_name="classsettings",
            name="mailchimp_api_key",
        ),
        migrations.RemoveField(
            model_name="classsettings",
            name="mailchimp_list_id",
        ),
    ]
