# Generated by Django 6.0.3 on 2026-04-25 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0011_remove_classsettings_google_analytics_measurement_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classsettings",
            name="enabled_publicly",
        ),
    ]
