# Generated by Django 6.0.2 on 2026-05-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0013_remove_enabled_publicly"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="wants_newsletter",
            field=models.BooleanField(
                default=False, help_text="Did the registrant tick the newsletter opt-in box at signup?"
            ),
        ),
    ]
