# Generated by Django 6.0.3 on 2026-03-23 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "registration_mode",
                    models.CharField(
                        choices=[("open", "Open"), ("invite_only", "Invite Only")],
                        default="invite_only",
                        help_text="Whether new users can register freely or only via invite.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the person being invited.", max_length=254, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the invite was created.")),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, help_text="When the invite was accepted by signing up.", null=True
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin user who sent this invite.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
