# Generated by Django 6.0.3 on 2026-03-23 04:52

from django.db import migrations


def create_default_config(apps, schema_editor):
    """Create the default SiteConfiguration singleton with invite_only mode."""
    SiteConfiguration = apps.get_model("core", "SiteConfiguration")
    SiteConfiguration.objects.get_or_create(pk=1, defaults={"registration_mode": "invite_only"})


def remove_default_config(apps, schema_editor):
    """Remove the default SiteConfiguration singleton."""
    SiteConfiguration = apps.get_model("core", "SiteConfiguration")
    SiteConfiguration.objects.filter(pk=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_siteconfiguration_invite"),
    ]

    operations = [
        migrations.RunPython(create_default_config, remove_default_config),
    ]
