# Generated by Django 6.0.3 on 2026-03-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_default_siteconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='registration_mode',
            field=models.CharField(choices=[('open', 'Open'), ('invite_only', 'Invite Only')], default='invite_only', help_text='Open — anyone can sign up. Invite Only — only people with an invite can register.', max_length=20),
        ),
    ]
