# Generated by Django 6.0.3 on 2026-03-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_site_configuration_to_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='registration_mode',
            field=models.CharField(choices=[('open', 'Open'), ('invite_only', 'Invite Only')], default='invite_only', help_text='Open — anyone can sign up. Invite Only — only people with an invite can register.', max_length=20, verbose_name='New User Registration Mode'),
        ),
    ]
