# Generated by Django 6.0.3 on 2026-03-23 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_update_registration_mode_verbose_name"),
        ("membership", "0012_unify_invites_into_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="member",
            field=models.OneToOneField(
                blank=True,
                help_text="The pre-created Member record for this invite.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invite",
                to="membership.member",
            ),
        ),
    ]
