# Generated by Django 6.0.3 on 2026-04-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_unify_invites_into_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="general_calendar_color",
            field=models.CharField(
                blank=True,
                default="#EEB44B",
                help_text="Hex color for general makerspace events on the Community Calendar (e.g. #EEB44B).",
                max_length=7,
                verbose_name="General Calendar Color",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="general_calendar_last_fetched_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the general calendar was last synced. Set by the calendar service.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="general_calendar_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Public iCal URL for the general makerspace calendar. Paste the 'Secret address in iCal format' from Google Calendar settings.",
                verbose_name="General Calendar iCal URL",
            ),
        ),
    ]
