# Generated by Django 6.0.3 on 2026-04-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_siteconfiguration_calendar_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="classes_last_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When classes were last synced from classes.pastlives.space. Set by the calendar service.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="sync_classes_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, upcoming classes are imported into the Community Calendar with links to register.",
                verbose_name="Sync classes from classes.pastlives.space",
            ),
        ),
    ]
