# Generated by Django 6.0.3 on 2026-04-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_siteconfiguration_classes_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="google_analytics_measurement_id",
            field=models.CharField(
                blank=True,
                help_text="GA4 measurement ID (e.g. G-XXXXXXX) — injected on the public classes portal. Leave blank to disable.",
                max_length=50,
                verbose_name="Google Analytics measurement ID",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="mailchimp_api_key",
            field=models.CharField(
                blank=True,
                help_text="MailChimp API key used for auto-subscribe on class registration and other integrations. Leave blank to disable.",
                max_length=255,
                verbose_name="MailChimp API key",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="mailchimp_list_id",
            field=models.CharField(
                blank=True,
                help_text="MailChimp list (audience) ID new subscribers are added to.",
                max_length=255,
                verbose_name="MailChimp list / audience ID",
            ),
        ),
    ]
