# Generated by Django 6.0.2 on 2026-05-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_siteconfiguration_google_analytics_measurement_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="google_analytics_measurement_id",
            field=models.CharField(
                blank=True,
                help_text="GA4 measurement ID (e.g. G-XXXXXXX) — injected site-wide (excludes the Django admin). Leave blank to disable.",
                max_length=50,
                verbose_name="Google Analytics measurement ID",
            ),
        ),
    ]
