# Generated by Django 6.0.1 on 2026-02-27 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0003_lease_index_and_guildvote_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="sublet_guild",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sublets",
                to="membership.guild",
            ),
        ),
    ]
