# Generated by Django 6.0.2 on 2026-03-01 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0004_space_sublet_guild"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="guilds/"),
        ),
        migrations.AddField(
            model_name="guild",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="guild",
            name="icon",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="guild",
            name="intro",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="guild",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="guild",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="GuildDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="guild_docs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="membership.guild"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Guild Document",
                "verbose_name_plural": "Guild Documents",
                "ordering": ["guild", "name"],
            },
        ),
        migrations.CreateModel(
            name="GuildWishlistItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="wishlist/")),
                ("link", models.URLField(blank=True)),
                ("estimated_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("is_fulfilled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guild Wishlist Item",
                "verbose_name_plural": "Guild Wishlist Items",
                "ordering": ["guild", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemberSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_schedule",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Schedule",
                "verbose_name_plural": "Member Schedules",
                "ordering": ["user"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Sunday"),
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_recurring", models.BooleanField(default=True)),
                (
                    "member_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="membership.memberschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Block",
                "verbose_name_plural": "Schedule Blocks",
                "ordering": ["member_schedule", "day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="GuildMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_lead", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="membership.guild"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guild_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Guild Membership",
                "verbose_name_plural": "Guild Memberships",
                "ordering": ["guild", "user"],
                "unique_together": {("guild", "user")},
            },
        ),
    ]
