# Generated by Django 6.0.2 on 2026-03-03 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0004_space_sublet_guild"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="guilds/"),
        ),
        migrations.AddField(
            model_name="guild",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="guild",
            name="icon",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="guild",
            name="intro",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="guild",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="guild",
            name="links",
            field=models.JSONField(blank=True, default=list, help_text="List of {name, url} dicts"),
        ),
        migrations.AddField(
            model_name="guild",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="Buyable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="buyables/")),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="buyables", to="membership.guild"
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyable",
                "verbose_name_plural": "Buyables",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GuildMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_lead", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="membership.guild"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guild_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Guild Membership",
                "verbose_name_plural": "Guild Memberships",
                "ordering": ["guild", "user"],
            },
        ),
        migrations.CreateModel(
            name="GuildWishlistItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="wishlist/")),
                ("link", models.URLField(blank=True)),
                ("estimated_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("is_fulfilled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guild Wishlist Item",
                "verbose_name_plural": "Guild Wishlist Items",
                "ordering": ["guild", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("amount", models.IntegerField(help_text="Total in cents")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("paid", "Paid"), ("failed", "Failed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("stripe_checkout_session_id", models.CharField(blank=True, max_length=255)),
                ("is_fulfilled", models.BooleanField(default=False)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="orders", to="membership.buyable"
                    ),
                ),
                (
                    "fulfilled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fulfilled_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="buyable",
            constraint=models.UniqueConstraint(fields=("guild", "slug"), name="unique_guild_buyable_slug"),
        ),
        migrations.AlterUniqueTogether(
            name="guildmembership",
            unique_together={("guild", "user")},
        ),
    ]
