# Generated by Django 6.0.2 on 2026-03-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0005_favoriteevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="guilds/covers/"),
        ),
        migrations.AddField(
            model_name="guild",
            name="description",
            field=models.TextField(blank=True, help_text="Full description"),
        ),
        migrations.AddField(
            model_name="guild",
            name="icon",
            field=models.CharField(blank=True, help_text="Material icon name", max_length=100),
        ),
        migrations.AddField(
            model_name="guild",
            name="intro",
            field=models.CharField(blank=True, help_text="Short one-line introduction", max_length=500),
        ),
        migrations.AddField(
            model_name="guild",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="guild",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
