# Generated by Django 6.0.2 on 2026-03-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_guild_cover_image_guild_description_guild_icon_and_more'),
        ('membership', '0005_guild_voting_system'),
    ]

    operations = [
    ]
