# Generated by Django 6.0.3 on 2026-03-05 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_guild_cover_image_guild_description_guild_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('calculated', 'Calculated')], default='draft', max_length=20)),
                ('eligible_member_count', models.PositiveIntegerField(default=0)),
                ('votes_cast', models.PositiveIntegerField(default=0)),
                ('results_summary', models.JSONField(blank=True, default=dict)),
                ('airtable_record_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voting Session',
                'verbose_name_plural': 'Voting Sessions',
                'ordering': ['-open_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='guildvote',
            options={'ordering': ['session', 'member_airtable_id', 'priority'], 'verbose_name': 'Guild Vote', 'verbose_name_plural': 'Guild Votes'},
        ),
        migrations.RemoveConstraint(
            model_name='guildvote',
            name='unique_member_priority',
        ),
        migrations.RemoveConstraint(
            model_name='guildvote',
            name='unique_member_guild',
        ),
        migrations.AddField(
            model_name='guildvote',
            name='airtable_record_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='guildvote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='guildvote',
            name='member_airtable_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='guildvote',
            name='member_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='guildvote',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_votes_received', to='membership.guild'),
        ),
        migrations.AlterField(
            model_name='guildvote',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guild_votes', to='membership.member'),
        ),
        migrations.AddField(
            model_name='guildvote',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='membership.votingsession'),
        ),
        migrations.AddConstraint(
            model_name='guildvote',
            constraint=models.UniqueConstraint(fields=('session', 'member_airtable_id', 'priority'), name='unique_session_member_priority'),
        ),
        migrations.AddConstraint(
            model_name='guildvote',
            constraint=models.UniqueConstraint(fields=('session', 'member_airtable_id', 'guild'), name='unique_session_member_guild'),
        ),
    ]
