# Generated by Django 6.0.2 on 2026-03-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_persistent_guild_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='show_in_directory',
            field=models.BooleanField(default=False),
        ),
    ]
