# Generated by Django 6.0.3 on 2026-03-22 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0008_show_in_directory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingsnapshot",
            name="contributor_count",
            field=models.PositiveIntegerField(
                help_text="Number of paying members who contributed to the funding pool."
            ),
        ),
        migrations.AlterField(
            model_name="fundingsnapshot",
            name="cycle_label",
            field=models.CharField(
                help_text="Human-readable label for the funding cycle (e.g. 'March 2026').", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="fundingsnapshot",
            name="funding_pool",
            field=models.DecimalField(
                decimal_places=2, help_text="Total dollar pool (contributor_count × $10).", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="fundingsnapshot",
            name="results",
            field=models.JSONField(default=dict, help_text="Full calculation results including per-guild breakdowns."),
        ),
        migrations.AlterField(
            model_name="fundingsnapshot",
            name="snapshot_at",
            field=models.DateTimeField(auto_now_add=True, help_text="When this snapshot was taken."),
        ),
        migrations.AlterField(
            model_name="member",
            name="show_in_directory",
            field=models.BooleanField(
                default=False, help_text="Whether this member appears in the public member directory."
            ),
        ),
        migrations.AlterField(
            model_name="votepreference",
            name="guild_1st",
            field=models.ForeignKey(
                help_text="First-choice guild (5 points).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_choice_votes",
                to="membership.guild",
            ),
        ),
        migrations.AlterField(
            model_name="votepreference",
            name="guild_2nd",
            field=models.ForeignKey(
                help_text="Second-choice guild (3 points).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="second_choice_votes",
                to="membership.guild",
            ),
        ),
        migrations.AlterField(
            model_name="votepreference",
            name="guild_3rd",
            field=models.ForeignKey(
                help_text="Third-choice guild (2 points).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="third_choice_votes",
                to="membership.guild",
            ),
        ),
        migrations.AlterField(
            model_name="votepreference",
            name="member",
            field=models.OneToOneField(
                help_text="The member who cast this vote.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vote_preference",
                to="membership.member",
            ),
        ),
        migrations.AlterField(
            model_name="votepreference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="When this vote was last changed."),
        ),
    ]
