# Generated by Django 6.0.3 on 2026-03-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0009_alter_fundingsnapshot_contributor_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guild",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Whether this guild is eligible for voting and display."),
        ),
    ]
