# Generated by Django 6.0.3 on 2026-03-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0011_seed_default_membership_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="status",
            field=models.CharField(
                choices=[
                    ("invited", "Invited"),
                    ("active", "Active"),
                    ("former", "Former"),
                    ("suspended", "Suspended"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
