# Generated by Django 6.0.3 on 2026-03-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0012_unify_invites_into_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingsnapshot",
            name="airtable_record_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Airtable record ID for bidirectional sync.",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="airtable_record_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Airtable record ID for bidirectional sync.",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="airtable_record_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Airtable record ID for bidirectional sync.",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="space",
            name="airtable_record_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Airtable record ID for bidirectional sync.",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="votepreference",
            name="airtable_record_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Airtable record ID for bidirectional sync.",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
