# Generated by Django 6.0.3 on 2026-03-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0013_add_airtable_record_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="role",
            new_name="member_type",
        ),
        migrations.AlterField(
            model_name="member",
            name="member_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("guild_lead", "Guild Lead"),
                    ("work_trade", "Work-Trade"),
                    ("employee", "Employee"),
                    ("contractor", "Contractor"),
                    ("volunteer", "Volunteer"),
                ],
                default="standard",
                help_text="What kind of member (standard, guild lead, work-trade, etc.).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="fog_role",
            field=models.CharField(
                choices=[("member", "Member"), ("guild_officer", "Guild Officer"), ("admin", "Admin")],
                default="member",
                help_text="FOG access level: admin (full access), guild officer (no site settings), member (hub only).",
                max_length=20,
            ),
        ),
    ]
