# Generated by Django 6.0.3 on 2026-03-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0014_rename_role_to_member_type_add_fog_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="about_me",
            field=models.TextField(blank=True, help_text="Short bio shown in the member directory."),
        ),
        migrations.AddField(
            model_name="member",
            name="discord_handle",
            field=models.CharField(blank=True, help_text="Discord username (e.g. user#1234 or @user).", max_length=100),
        ),
        migrations.AddField(
            model_name="member",
            name="other_contact_info",
            field=models.CharField(
                blank=True, help_text="Other ways to reach this member (Instagram, Signal, etc.).", max_length=255
            ),
        ),
    ]
