# Generated by Django 6.0.3 on 2026-03-30 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0016_add_pronouns_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberEmail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(help_text="An email address for this member.", max_length=254, unique=True),
                ),
                ("is_primary", models.BooleanField(default=False, help_text="Primary email shown in lists.")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="emails", to="membership.member"
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Alias",
                "verbose_name_plural": "Email Aliases",
                "ordering": ["-is_primary", "email"],
            },
        ),
    ]
