# Generated by Django 6.0.3 on 2026-04-02 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0017_memberemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberemail",
            name="member",
            field=models.ForeignKey(
                help_text="The member this email belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="membership.member",
            ),
        ),
    ]
