# Generated by Django 6.0.2 on 2026-04-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0018_alter_memberemail_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='about',
            field=models.TextField(blank=True, default='', help_text='Member-facing description or announcement shown on the guild page.'),
        ),
    ]
