# Generated by Django 6.0.3 on 2026-04-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0019_guild_about"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="email",
            new_name="_pre_signup_email",
        ),
        migrations.AlterField(
            model_name="member",
            name="_pre_signup_email",
            field=models.EmailField(
                blank=True,
                db_column="email",
                default="",
                help_text="Stored email used ONLY when this Member has no linked User. Once a User is linked, allauth.account.EmailAddress becomes the source of truth; read `member.primary_email` instead. See docs/superpowers/specs/2026-04-07-user-email-aliases-design.md for the full architecture.",
                max_length=254,
            ),
        ),
    ]
