# Generated by Django 6.0.3 on 2026-04-08 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0020_rename_member_email_to_pre_signup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memberemail",
            options={
                "ordering": ["email"],
                "verbose_name": "Staged Email (pre-signup)",
                "verbose_name_plural": "Staged Emails (pre-signup)",
            },
        ),
        migrations.RemoveField(
            model_name="memberemail",
            name="is_primary",
        ),
        migrations.AlterField(
            model_name="memberemail",
            name="email",
            field=models.EmailField(help_text="A staged email address for this member.", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="memberemail",
            name="member",
            field=models.ForeignKey(
                help_text="The unlinked member this staged email belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="membership.member",
            ),
        ),
    ]
