# Generated by Django 6.0.2 on 2026-04-09 21:23

import django.core.serializers.json
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0022_seed_allauth_emailaddresses"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingsnapshot",
            name="minimum_pool",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Minimum dollar floor applied to the funding pool at snapshot time. New snapshots default to $1,000; historical snapshots default to 0 so their original numbers are preserved.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="fundingsnapshot",
            name="raw_votes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Frozen list of individual votes at snapshot time. Each entry has member_id, member_name, member_type, fog_role, is_paying, and the three guild picks (id + name). Drives the admin analyzer view.",
            ),
        ),
        migrations.AlterField(
            model_name="fundingsnapshot",
            name="funding_pool",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total dollar pool (max of paying_voters × $10 and minimum_pool).",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="fundingsnapshot",
            name="results",
            field=models.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Full calculation results including per-guild breakdowns. Decimals are serialized as strings.",
            ),
        ),
    ]
