# Generated by Django 6.0.4 on 2026-04-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0023_fundingsnapshot_minimum_pool_raw_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='officers',
            field=models.ManyToManyField(blank=True, help_text='Members who hold an officer role in this guild (besides the lead).', related_name='officer_of_guilds', to='membership.member'),
        ),
    ]
