# Generated by Django 6.0.3 on 2026-04-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0023_fundingsnapshot_minimum_pool_raw_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="calendar_color",
            field=models.CharField(
                blank=True,
                default="#4B9FEE",
                help_text="Hex color code for this guild's events on the Community Calendar (e.g. #4B9FEE).",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="guild",
            name="calendar_last_fetched_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this guild's iCal feed was last synced. Set by the calendar service.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="guild",
            name="calendar_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Public iCal URL for this guild's Google Calendar (File → Share → Get shareable iCal link).",
            ),
        ),
    ]
