# Generated by Django 6.0.4 on 2026-04-14 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0024_guild_officers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='officers',
        ),
        migrations.CreateModel(
            name='GuildOfficerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Free-text role title, e.g. Treasurer, Secretary, Instructor.', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_roles', to='membership.guild')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_roles', to='membership.member')),
            ],
            options={
                'ordering': ['title', 'member__full_legal_name'],
                'constraints': [models.UniqueConstraint(fields=('guild', 'member', 'title'), name='uq_guild_officer_role')],
            },
        ),
    ]
