# Generated by Django 6.0.3 on 2026-04-15 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0024_guild_calendar_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.CharField(db_index=True, help_text="iCal UID, unique within a source.", max_length=500)),
                ("title", models.CharField(help_text="Event title from iCal SUMMARY field.", max_length=500)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Event description from iCal DESCRIPTION field."),
                ),
                (
                    "location",
                    models.CharField(blank=True, help_text="Event location from iCal LOCATION field.", max_length=500),
                ),
                ("url", models.URLField(blank=True, help_text="Event URL from iCal URL field.")),
                ("start_dt", models.DateTimeField(help_text="Event start time, UTC-normalized.")),
                ("end_dt", models.DateTimeField(help_text="Event end time, UTC-normalized.")),
                (
                    "all_day",
                    models.BooleanField(
                        default=False, help_text="True for all-day events (DATE not DATETIME in iCal)."
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(help_text="When this record was last synced from the iCal source."),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        help_text="Guild this event belongs to. Null for general makerspace events.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Event",
                "verbose_name_plural": "Calendar Events",
                "ordering": ["start_dt"],
                "indexes": [
                    models.Index(fields=["start_dt", "end_dt"], name="idx_calendarevent_start_end"),
                    models.Index(fields=["guild", "uid"], name="idx_calendarevent_guild_uid"),
                ],
            },
        ),
    ]
