# Generated by Django 6.0.3 on 2026-04-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0025_calendarevent"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="calendarevent",
            name="idx_calendarevent_guild_uid",
        ),
        migrations.AddConstraint(
            model_name="calendarevent",
            constraint=models.UniqueConstraint(fields=("guild", "uid"), name="uq_calendarevent_guild_uid"),
        ),
    ]
