# Generated by Django 6.0.4 on 2026-04-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0025_remove_guild_officers_guildofficerrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='officers',
            field=models.ManyToManyField(blank=True, help_text='Members holding a titled officer role in this guild (besides the lead).', related_name='officer_of_guilds', through='membership.GuildOfficerRole', to='membership.member'),
        ),
    ]
