# Generated by Django 6.0.3 on 2026-04-22 05:47

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0027_calendarevent_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                help_text="Banner image shown at the top of the guild page.",
                upload_to="guilds/banners/",
                validators=[core.validators.validate_image_size],
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                help_text="Profile photo shown in the member directory.",
                upload_to="members/profile/",
                validators=[core.validators.validate_image_size],
            ),
        ),
        migrations.AlterField(
            model_name="space",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Optional photo of the space, shown on the space detail page.",
                upload_to="spaces/",
                validators=[core.validators.validate_image_size],
            ),
        ),
    ]
