"""App version and changelog."""

from __future__ import annotations

VERSION = "1.7.7"

CHANGELOG: list[dict[str, str | list[str]]] = [
    {
        "version": "1.7.7",
        "date": "2026-04-27",
        "title": "Hotfix: site layout broken for everyone",
        "changes": [
            "Fixed a bug introduced in the last release where the entire site rendered at half-width with a stray line of text near the top — the page was unusable. Everything looks correct again.",
        ],
    },
    {
        "version": "1.7.6",
        "date": "2026-04-26",
        "title": "Free classes & workshops — and a fix for the Register page styling",
        "changes": [
            'When you create or edit a class, there\'s now a "This is a free class / workshop" checkbox right above the price field. Tick it and the class is free — members and visitors register without entering any payment info, and they get a confirmation email immediately.',
            'Free classes show as "Free" everywhere on the site (the class card, the detail page, and the registration summary) instead of a $0 price tag.',
            "Fixed a bug where the Register page on a class could load with no styling if you clicked through from another page in the same browser tab. The page now keeps its full styling no matter how you arrive at it.",
        ],
    },
    {
        "version": "1.7.5",
        "date": "2026-04-25",
        "title": "Members can sign up for classes online — plus a unified Classes page",
        "changes": [
            "You can now register for classes and workshops directly on the website. Click Register on any class page, fill out a short form, sign the liability waiver online, and pay with a card through Stripe — no more email back-and-forth.",
            "Members get the member discount applied automatically when the email on the form matches a verified member email.",
            "Free classes skip the payment step and confirm immediately — you'll get a confirmation email right away.",
            "Discount codes are honored on the registration form, and stack on top of the member discount.",
            "Every confirmed registrant gets a confirmation email with the schedule, location, and a personal link they can use to view or cancel their spot — no login needed.",
            "There's now a single Classes & Workshops page in the sidebar — the same page everyone sees, members and visitors alike. Admins and instructors get a Manage button right on that page that opens the classes admin (or the Teaching dashboard for instructors), so you don't lose anything, it's just one entry point instead of two.",
            'Fixed: a class you publish now shows up on the Classes & Workshops page right away, even before its sessions are scheduled — it appears with an "Upcoming dates TBA" note until you add dates.',
        ],
    },
    {
        "version": "1.7.4",
        "date": "2026-04-25",
        "title": "One unified view — Classes, Calendar, Payments, and admin all live in the FOG dashboard",
        "changes": [
            "The Classes page at /classes/ is now public for everyone — no admin toggle needed.",
            "Everything now lives inside the FOG dashboard with the same sidebar and topnav. No more bouncing into a different admin layout — Classes, Community Calendar, Payments, Reports, Manage Members, Site Settings, and the new Voting Dashboard all open in the hub.",
            "Admins see one sidebar with everything they need: Community Calendar, Manage Classes, Manage Members, Member Directory, My Tab, Payments, Reports, Site Settings, and Voting Dashboard.",
            'The "Viewing as" dropdown stays in the topbar so admins can preview the hub as a Member, Guild Officer, Instructor, or Guest without switching accounts.',
            'All instructors are members by default — the "Non-member Instructor" label is gone, instructors are just instructors.',
        ],
    },
    {
        "version": "1.7.3",
        "date": "2026-04-23",
        "title": "Classes: public portal, instructor dashboard, and calendar integration",
        "changes": [
            "Browse classes at a new public page at /classes/ — grouped by category with sticky filters, hero, and polished card grid; gated behind an admin toggle in Classes → Settings so it only goes live when you're ready",
            "Class detail and instructor profile pages with schedule, description, pricing, member discount, and links back to the portal",
            "New Teaching section in the hub sidebar for instructors — lets them see their classes, submit drafts for admin review, view their registrations, and edit their own profile (photo, bio, website, social handle)",
            "Classes admin gets a status filter (All / Draft / Pending / Published / Archived) with live counts and dims archived rows, plus a Delete button for drafts with zero registrations — Archive preserves history; Delete is only for cleanup",
            "Published local classes now show up on the Community Calendar alongside the external feed during the transition period",
            "Scheduled reminder email infrastructure in place — `manage.py send_class_reminders` emails confirmed registrants for sessions starting soon (reminder window configurable in Classes → Settings)",
            "Small admin polish: shortened URLs from /classes/admin/classes/ → /classes/admin/, 'View public portal' link in the Classes admin header, proper small red delete buttons with confirmation modals across Categories, Discount Codes, and Classes",
        ],
    },
    {
        "version": "1.7.2",
        "date": "2026-04-23",
        "title": "Fix: logout page styling",
        "changes": [
            "Fixed the logout confirmation page so it uses the normal Past Lives site styling instead of showing an unstyled default page",
        ],
    },
    {
        "version": "1.7.1",
        "date": "2026-04-21",
        "title": "Photos for member profiles, guild banners, and classes",
        "changes": [
            "You can now upload a profile photo on your User Settings → Profile page — your photo replaces your initials in the member directory and in the top-right of the navbar",
            "Guild leads can add a banner image to their guild's page — it appears at the top of the guild detail page above the name and About section, with a tooltip explaining the recommended dimensions",
            "Class images (categories, instructors, and individual classes) and other photos uploaded through the admin now stay around between deploys instead of disappearing",
            "Image uploads have a 5 MB limit so things stay snappy and don't blow up our storage bill",
            "Replacing or removing a photo now also deletes the old file from storage so we don't accumulate orphaned images over time",
            "Friendlier image-upload UI everywhere — the small 'Currently / Clear checkbox' has been replaced with a thumbnail preview and a small red 'Remove' (or 'Delete photo') button that asks for confirmation before deleting",
        ],
    },
    {
        "version": "1.7.0.2",
        "date": "2026-04-21",
        "title": "Hotfix: deploy failing on Render",
        "changes": [
            "Fixed a deploy failure that was blocking new releases from going live on Render — the build step that packages up static files was being rejected because it couldn't see the production database settings. It now uses a harmless placeholder just for that build step, so deploys go through again",
        ],
    },
    {
        "version": "1.7.0.1",
        "date": "2026-04-21",
        "title": "Classes: admin tabs foundation",
        "changes": [
            "New Classes admin area (admins only) with six tabs — Classes, Categories, Instructors, Registrations, Discount Codes, and Settings — so we can build out the makerspace's class catalog natively inside Past Lives without needing the old booking site",
            "Admins can create categories, invite instructors (who get their own login), build classes with a full set of fields (prerequisites, materials, capacity, member discount, scheduling), and manage discount codes — the public registration flow + Stripe payments come in a follow-up release",
            'Instructors now exist as a first-class role: someone can be a member, an instructor, or both. The "Viewing as" dropdown recognizes the new role so admins can preview what teachers see',
            "Class titles and category names auto-fill the URL slug as you type — saves a step every time you make a new one",
        ],
    },
    {
        "version": "1.6.3",
        "date": "2026-04-17",
        "title": "Admin role preview in the hub",
        "changes": [
            'Admins and guild officers now have a new "Viewing as" button in the topbar — use it to preview the hub the way a plain member or guild officer would see it, without logging out. Unchecking a role hides that role\'s UI for the current session only.',
        ],
    },
    {
        "version": "1.6.2",
        "date": "2026-04-15",
        "title": "Fix: login page CSS broken after navigating from the hub",
        "changes": [
            "Fixed a bug where navigating to a protected page with an expired session would redirect you to the login page with completely broken styles — it now does a proper full-page load so the login page looks correct",
        ],
    },
    {
        "version": "1.6.1",
        "date": "2026-04-15",
        "title": "Calendar: Classes sync, configurable colors & pagination",
        "changes": [
            "Classes from classes.pastlives.space now show up on the Community Calendar — click the title to go straight to the registration page",
            "Classes have their own color on the calendar, separate from General events — customize it in Site Settings",
            "The event list now shows 10 events per page with prev/next arrows so the page doesn't get overwhelmed",
            "Admins can configure the Classes color in Site Settings → Community Calendar alongside the existing General color",
        ],
    },
    {
        "version": "1.6.0",
        "date": "2026-04-15",
        "title": "Community Calendar",
        "changes": [
            "New Community Calendar — see all upcoming makerspace events in one place, with week and month views so you can plan ahead",
            "Filter events by guild to find workshops, meetups, and events from just the guilds you care about",
            "Export any event to your personal calendar app (Google, Apple, Outlook — whatever you use) with one click",
            "Guild officers can now link their guild's Google Calendar so events sync automatically — no more posting events in two places",
        ],
    },
    {
        "version": "1.5.7",
        "date": "2026-04-15",
        "title": "Current Vote Standings — real totals",
        "changes": [
            "Current Vote Standings now show the real point totals — a guild that picked up votes at multiple ranks (say, one 1st, two 2nds, and three 3rds) was being displayed with those counts multiplied together instead of added, so some guilds were appearing at 60 points when the actual total was 17. Fixed on the Guild Voting page and the admin dashboard",
        ],
    },
    {
        "version": "1.5.6",
        "date": "2026-04-15",
        "title": "Voting hotfixes, User Settings, and sidebar polish",
        "changes": [
            "The Guild Voting page is now split into three tabs: Current Standings (live points), New Votes This Month (only votes cast or changed since the last snapshot), and Last Month's Results (the most recent snapshot with funding breakdown)",
            "Your vote still rolls over automatically every cycle — once you've submitted it, it stays in place and keeps counting until you change it",
            "The admin Voting Preferences page now shows a per-member voting history pulled from past snapshots, so you can audit how anyone's picks contributed to the totals cycle by cycle",
            "New unified User Settings page at /settings/ with Profile and Emails tabs — the old Manage Email Addresses page that looked like the login screen is gone, and adding/removing/verifying emails now happens inside the hub layout",
            "On the Emails tab, Manage Email Addresses and Email Preferences are now two separate cards, and the Re-send Verification button only appears when the selected email isn't verified yet",
            "The user menu in the top-right is now just Settings + Log Out — everything else lives inside the new User Settings page",
            "Resources links (Member Guide + Code of Conduct) and Feedback now live together in the bottom of the left sidebar, each styled consistently with the rest of the nav — no more floating button overlapping other content",
            "Fixed a Postgres error that was blocking the last deploy on Render — the migration that clears legacy product data and drops old columns now commits its cleanup before altering the schema, so the two steps can't collide in a single transaction",
        ],
    },
    {
        "version": "1.5.5",
        "date": "2026-04-14",
        "title": "Edit products in place",
        "changes": [
            "You can now edit a product right from your guild page — click the small pencil on a product card and the same pop-up you use to add products opens up pre-filled with that product's name, price, and revenue split",
            "Saving updates the product in place — no need to delete and re-add it just to fix a typo or change the percentages",
            "Product cards are cleaner — the 'Admin 20% · Guild 80%' split summary is hidden now that you can see and edit the same info from the product's edit pop-up",
        ],
    },
    {
        "version": "1.5.4",
        "date": "2026-04-14",
        "title": "Edit Your Guild Page Directly",
        "changes": [
            "Guild leads can now edit their guild's page without going through the admin — just open your guild page and you'll see an 'Edit Guild Page' button next to the title and an 'Add Product' button in the Products section",
            "Admins and guild officers see the same edit buttons on every guild page",
            "Changing the guild name or description happens right in a pop-up window on the guild page",
            "Adding a new product now opens a pop-up with the revenue-split builder instead of sending you to the admin panel — closing and re-opening the pop-up resets it cleanly",
            "Existing products show a small delete button in the corner so you can remove them without leaving the page",
            "The old 'Guilds' entry in the admin panel is gone — everything guild-related lives on the public guild pages now",
            "My Tab page now has a hoverable '?' next to the title that explains how tabs work, and the next-charge date shows as subtext below the heading instead of buried in the middle of the card",
            "Small copy fix on guild pages so the payment-method prompt reads 'add items to your tab' instead of just 'add items'",
            "Sidebar 'Guilds' section starts expanded by default, and remembers your preference if you collapse it",
        ],
    },
    {
        "version": "1.5.3",
        "date": "2026-04-14",
        "title": "Flexible Product Revenue Splits",
        "changes": [
            "Products can now split revenue across multiple guilds and admin in any combination — for example, a $10 product can be set up so 20% goes to admin, 60% to the Ceramics Guild, and 20% to the Art Framing Guild",
            "The percentages have to add up to 100%, but otherwise you can mix recipients however you like",
            "The Add Product form has been redesigned: it now appears inline on the guild edit page (no more popup) with a live preview that shows exactly how a sale will be divided up",
            "The 'active/inactive' toggle is gone — if a product exists, it's available; if you delete it, it's gone",
            "Existing products and past tab entries were cleared during this upgrade — you'll need to re-add your products with their new split configuration",
        ],
    },
    {
        "version": "1.5.2",
        "date": "2026-04-14",
        "title": "Local Dev Setup & Cart Toast Fix",
        "changes": [
            "New developer setup: clone the repo, run make setup, make db-up, make server — and you're running locally with PostgreSQL",
            "New 'make db-pull-prod' command downloads a copy of the production database for local testing",
            "Login codes now appear directly on screen during local development — no more checking the terminal",
            "The 'added to cart' notification now appears in the center of the screen instead of covering the tab balance",
        ],
    },
    {
        "version": "1.5.1",
        "date": "2026-04-13",
        "title": "My Tab & Guild Page Hotfixes",
        "changes": [
            "My Tab page redesigned: Current Balance and Pending Charges are combined into one card, and Payment Method now lives at the bottom",
            "My Tab page now shows your saved card with a link to add, replace, or remove it",
            "My Tab page tells you when your tab will be processed by Stripe so there are no surprises",
            "Removing a pending charge from your tab is now a one-click trash button — no confirmation dialog",
            "Removed the 'Add to Tab' form from the My Tab page — add items from guild pages instead",
            "Guild pages now have a 'General Consumables' card with a quantity picker so you can add custom-priced items directly to your tab",
            "Fixed a bug where one action would show two toast notifications at once",
            "Cleaner spacing between cards on the My Tab page and the payment-method setup page",
        ],
    },
    {
        "version": "1.5.0",
        "date": "2026-04-11",
        "title": "Single Stripe Account, Revenue Splits & Reports",
        "changes": [
            "Billing now runs through a single Past Lives Stripe account — each guild no longer links its own account separately",
            "Every charge has a configurable admin/guild percentage split (20% / 80% by default) — set site-wide or per-product",
            "New 'split equally across all guilds' option on any product or custom charge — the guild share gets divided evenly between active guilds",
            "New 'Enter Your Own Price' form on every guild page — add a custom-price item to your tab without an officer creating a product first",
            "Guild product cards now have an 'Add to tab' button so members can add items in one click from the guild page",
            "New admin Reports page (Payments → Reports) with date/guild/status filters and CSV export — shows exactly how much to pay each guild",
            "Product editor on the admin now includes admin % and split-mode controls for officers",
            "Saved card required again for tab entries (the direct-keys Checkout flow is gone)",
            "Cleanup: removed Stripe Connect OAuth flow, per-guild direct-keys management, and per-guild webhook endpoints — they're no longer needed",
        ],
    },
    {
        "version": "1.4.1",
        "date": "2026-04-11",
        "title": "Funding Results — Quieter Display & Admin Email Aliases",
        "changes": [
            "The funding results section no longer shows how many members contributed to each snapshot — keeping that detail private for now",
            "Admins can now add email aliases directly from the member page — handy for shared addresses like guild mailboxes where the member can't easily receive a verification code themselves",
            "Admins can also remove aliases, change which one is primary, and toggle whether an alias is marked verified",
            "Fixed a quiet bug where changing your primary email could silently revert on the next save — primary changes now stick",
        ],
    },
    {
        "version": "1.4.0",
        "date": "2026-04-11",
        "title": "Email Aliases & Smarter Funding Snapshots",
        "changes": [
            "New 'Manage email addresses' page in your profile menu — add, remove, verify, and set a primary email all in one place",
            "Sign in with any of your verified email addresses, not just the one you signed up with",
            "Cleaner admin: removed the confusing 'is primary' toggle on member email aliases",
            "Funding snapshots now have a $1,000 minimum pool so small-turnout months still allocate meaningful amounts to guilds",
            "New Snapshot Analyzer admin page — preview live vote results with filters by member type, role, and paying status before taking a snapshot",
            "Stored snapshots can be re-sliced with the same filters to see exactly who voted for what",
            "Admins can now delete a snapshot from the analyzer page",
            "Fixed: non-paying guild officers' votes are no longer silently zeroed out when the funding pool is calculated",
        ],
    },
    {
        "version": "1.3.2",
        "date": "2026-04-07",
        "title": "Pay-as-you-go Tabs, Guild Product Cards & Stripe in Settings",
        "changes": [
            "You no longer need to save a card before adding things to your tab — just add the item and pay later",
            "When you have charges ready to pay, a 'Pay Now' button appears on your Tab page that opens Stripe's secure checkout",
            "Money goes directly to the guild that owns the items you bought",
            "Guild pages now show products as cards instead of a table — easier to scan",
            "All Stripe configuration now lives in the admin Payments → Settings page — no more editing server environment variables",
            "Stripe Connect platform billing can now be enabled with a single toggle in Settings (for future membership and space-lease billing)",
        ],
    },
    {
        "version": "1.3.1",
        "date": "2026-04-07",
        "title": "Pay Guilds Directly for Consumables",
        "changes": [
            "Guilds can now connect their own Stripe account by pasting their API keys — no platform setup required",
            "Money for consumables (clay, materials, etc.) goes straight to the guild that owns the items",
            "Admins can test a guild's Stripe keys before saving to make sure everything is connected",
        ],
    },
    {
        "version": "1.3.0",
        "date": "2026-04-02",
        "title": "Tab Billing System",
        "changes": [
            "New tab system — charges accumulate on your tab and get billed on a schedule, just like a bar tab",
            "See your tab balance at a glance with the new balance pill in the top bar",
            "My Tab page shows your pending charges, tab limit, and remaining balance",
            "Tab History page shows all past charges with itemized details you can expand",
            "Add items to your own tab with the self-service form",
            "Set up a payment method securely through Stripe — your card info never touches our server",
            "Automated billing engine charges tabs on a configurable schedule (daily, weekly, or monthly)",
            "Failed charges automatically retry up to 3 times before locking the tab",
            "Email receipts after every successful charge with an itemized breakdown",
            "Guild Stripe accounts can be connected via Stripe Connect — each guild receives their share of charges directly",
            "Members can pick products when adding to their tab — price and description are filled in automatically",
            "Unified Payments admin — one page for outstanding tabs, charge history, billing settings, and Stripe accounts",
            "All financial records are preserved forever — entries are voided, never deleted",
            "Guild pages — each guild now has its own page with an about section and a list of products",
            "Guild leads can edit their guild's about text and manage their product listings directly from the guild page",
        ],
    },
    {
        "version": "1.2.1",
        "date": "2026-04-01",
        "title": "Mobile Sidebar Fix",
        "changes": [
            "Fixed the sidebar on mobile — it now slides open as a drawer with a dark backdrop you can tap to close",
            "Sidebar starts closed on mobile so you get the full screen for content",
            "Tapping a nav link on mobile automatically closes the sidebar",
        ],
    },
    {
        "version": "1.2.0",
        "date": "2026-03-30",
        "title": "Member Management Redesign",
        "changes": [
            "Admin Members page now lets you create users with a login right from the add form",
            "Added email aliases — members can have multiple email addresses and log in with any of them",
            "New 'Users' filter on the Members page to see who has logged into the app",
            "Search now finds members by their alias emails too",
            "Removed the separate User admin page — everything is managed through Members now",
        ],
    },
    {
        "version": "1.1.2",
        "date": "2026-03-30",
        "title": "Mobile Sidebar Fix",
        "changes": [
            "Fixed the sidebar menu button not working on Android phones — the side menu now opens and closes properly on mobile",
        ],
    },
    {
        "version": "1.1.1",
        "date": "2026-03-28",
        "title": "Better Discord Announcements",
        "changes": [
            "Discord now gets a friendly release announcement when updates go live — with version and what changed",
            "Removed noisy PR-opened notifications so the channel stays clean",
        ],
    },
    {
        "version": "1.1.0",
        "date": "2026-03-28",
        "title": "Vote Standings & Discord Notifications",
        "changes": [
            "Live vote standings with bar charts on the guild voting page — see who's leading in real time",
            "Admin voting dashboard now shows visual bar charts for vote leaders",
            "Discord notifications — the team gets pinged when PRs are opened or code is merged to main",
        ],
    },
    {
        "version": "1.0.3",
        "date": "2026-03-28",
        "title": "Login & Email Fixes",
        "changes": [
            "Members synced from Airtable can now log in immediately — no signup step needed",
            "All emails from Past Lives are now properly branded (no more 'example.com')",
            "Table columns in the admin panel are now left-aligned for easier reading",
        ],
    },
    {
        "version": "1.0.2",
        "date": "2026-03-28",
        "title": "Admin Fixes",
        "changes": [
            "Role management moved out of the member directory — it now lives in the admin panel only",
            "Login code entry allows up to 5 attempts before locking out (was 3)",
        ],
    },
    {
        "version": "1.0.1",
        "date": "2026-03-27",
        "title": "Hotfix",
        "changes": [
            "Guild vote history from before launch is now reflected in voting results",
            "Login code emails no longer show [example.com] in the subject line",
            "Login page email field now shows the correct placeholder",
        ],
    },
    {
        "version": "1.0.0",
        "date": "2026-03-27",
        "title": "Launch Day",
        "changes": [
            "Vote for your favorite guilds each month and see how funding gets split",
            "Your own member hub — one place for voting, directory, and settings",
            "Passwordless sign-in — just enter your email and we send you a code",
            "Member directory — find other members, see their bios and contact info",
            "Member roles — admins, guild officers, and regular members each see what they need",
            "Admins can invite new members, manage the roster, and take funding snapshots",
            "Send us feedback anytime from the Feedback button",
            "Works on your phone — install it like an app from your browser",
            "Forgot which email you signed up with? The new account finder has you covered",
        ],
    },
]
