"""App version and changelog."""

from __future__ import annotations

VERSION = "1.5.4"

CHANGELOG: list[dict[str, str | list[str]]] = [
    {
        "version": "1.5.4",
        "date": "2026-04-14",
        "title": "Edit Your Guild Page Directly",
        "changes": [
            "Guild leads can now edit their guild's page without going through the admin — just open your guild page and you'll see an 'Edit Guild Page' button next to the title and an 'Add Product' button in the Products section",
            "Admins and guild officers see the same edit buttons on every guild page",
            "Changing the guild name or description happens right in a pop-up window on the guild page",
            "Adding a new product now opens a pop-up with the revenue-split builder instead of sending you to the admin panel — closing and re-opening the pop-up resets it cleanly",
            "Existing products show a small delete button in the corner so you can remove them without leaving the page",
            "The old 'Guilds' entry in the admin panel is gone — everything guild-related lives on the public guild pages now",
            "My Tab page now has a hoverable '?' next to the title that explains how tabs work, and the next-charge date shows as subtext below the heading instead of buried in the middle of the card",
            "Small copy fix on guild pages so the payment-method prompt reads 'add items to your tab' instead of just 'add items'",
            "Sidebar 'Guilds' section starts expanded by default, and remembers your preference if you collapse it",
        ],
    },
    {
        "version": "1.5.3",
        "date": "2026-04-14",
        "title": "Flexible Product Revenue Splits",
        "changes": [
            "Products can now split revenue across multiple guilds and admin in any combination — for example, a $10 product can be set up so 20% goes to admin, 60% to the Ceramics Guild, and 20% to the Art Framing Guild",
            "The percentages have to add up to 100%, but otherwise you can mix recipients however you like",
            "The Add Product form has been redesigned: it now appears inline on the guild edit page (no more popup) with a live preview that shows exactly how a sale will be divided up",
            "The 'active/inactive' toggle is gone — if a product exists, it's available; if you delete it, it's gone",
            "Existing products and past tab entries were cleared during this upgrade — you'll need to re-add your products with their new split configuration",
        ],
    },
    {
        "version": "1.5.2",
        "date": "2026-04-14",
        "title": "Local Dev Setup & Cart Toast Fix",
        "changes": [
            "New developer setup: clone the repo, run make setup, make db-up, make server — and you're running locally with PostgreSQL",
            "New 'make db-pull-prod' command downloads a copy of the production database for local testing",
            "Login codes now appear directly on screen during local development — no more checking the terminal",
            "The 'added to cart' notification now appears in the center of the screen instead of covering the tab balance",
        ],
    },
    {
        "version": "1.5.1",
        "date": "2026-04-13",
        "title": "My Tab & Guild Page Hotfixes",
        "changes": [
            "My Tab page redesigned: Current Balance and Pending Charges are combined into one card, and Payment Method now lives at the bottom",
            "My Tab page now shows your saved card with a link to add, replace, or remove it",
            "My Tab page tells you when your tab will be processed by Stripe so there are no surprises",
            "Removing a pending charge from your tab is now a one-click trash button — no confirmation dialog",
            "Removed the 'Add to Tab' form from the My Tab page — add items from guild pages instead",
            "Guild pages now have a 'General Consumables' card with a quantity picker so you can add custom-priced items directly to your tab",
            "Fixed a bug where one action would show two toast notifications at once",
            "Cleaner spacing between cards on the My Tab page and the payment-method setup page",
        ],
    },
    {
        "version": "1.5.0",
        "date": "2026-04-11",
        "title": "Single Stripe Account, Revenue Splits & Reports",
        "changes": [
            "Billing now runs through a single Past Lives Stripe account — each guild no longer links its own account separately",
            "Every charge has a configurable admin/guild percentage split (20% / 80% by default) — set site-wide or per-product",
            "New 'split equally across all guilds' option on any product or custom charge — the guild share gets divided evenly between active guilds",
            "New 'Enter Your Own Price' form on every guild page — add a custom-price item to your tab without an officer creating a product first",
            "Guild product cards now have an 'Add to tab' button so members can add items in one click from the guild page",
            "New admin Reports page (Payments → Reports) with date/guild/status filters and CSV export — shows exactly how much to pay each guild",
            "Product editor on the admin now includes admin % and split-mode controls for officers",
            "Saved card required again for tab entries (the direct-keys Checkout flow is gone)",
            "Cleanup: removed Stripe Connect OAuth flow, per-guild direct-keys management, and per-guild webhook endpoints — they're no longer needed",
        ],
    },
    {
        "version": "1.4.1",
        "date": "2026-04-11",
        "title": "Funding Results — Quieter Display & Admin Email Aliases",
        "changes": [
            "The funding results section no longer shows how many members contributed to each snapshot — keeping that detail private for now",
            "Admins can now add email aliases directly from the member page — handy for shared addresses like guild mailboxes where the member can't easily receive a verification code themselves",
            "Admins can also remove aliases, change which one is primary, and toggle whether an alias is marked verified",
            "Fixed a quiet bug where changing your primary email could silently revert on the next save — primary changes now stick",
        ],
    },
    {
        "version": "1.4.0",
        "date": "2026-04-11",
        "title": "Email Aliases & Smarter Funding Snapshots",
        "changes": [
            "New 'Manage email addresses' page in your profile menu — add, remove, verify, and set a primary email all in one place",
            "Sign in with any of your verified email addresses, not just the one you signed up with",
            "Cleaner admin: removed the confusing 'is primary' toggle on member email aliases",
            "Funding snapshots now have a $1,000 minimum pool so small-turnout months still allocate meaningful amounts to guilds",
            "New Snapshot Analyzer admin page — preview live vote results with filters by member type, role, and paying status before taking a snapshot",
            "Stored snapshots can be re-sliced with the same filters to see exactly who voted for what",
            "Admins can now delete a snapshot from the analyzer page",
            "Fixed: non-paying guild officers' votes are no longer silently zeroed out when the funding pool is calculated",
        ],
    },
    {
        "version": "1.3.2",
        "date": "2026-04-07",
        "title": "Pay-as-you-go Tabs, Guild Product Cards & Stripe in Settings",
        "changes": [
            "You no longer need to save a card before adding things to your tab — just add the item and pay later",
            "When you have charges ready to pay, a 'Pay Now' button appears on your Tab page that opens Stripe's secure checkout",
            "Money goes directly to the guild that owns the items you bought",
            "Guild pages now show products as cards instead of a table — easier to scan",
            "All Stripe configuration now lives in the admin Payments → Settings page — no more editing server environment variables",
            "Stripe Connect platform billing can now be enabled with a single toggle in Settings (for future membership and space-lease billing)",
        ],
    },
    {
        "version": "1.3.1",
        "date": "2026-04-07",
        "title": "Pay Guilds Directly for Consumables",
        "changes": [
            "Guilds can now connect their own Stripe account by pasting their API keys — no platform setup required",
            "Money for consumables (clay, materials, etc.) goes straight to the guild that owns the items",
            "Admins can test a guild's Stripe keys before saving to make sure everything is connected",
        ],
    },
    {
        "version": "1.3.0",
        "date": "2026-04-02",
        "title": "Tab Billing System",
        "changes": [
            "New tab system — charges accumulate on your tab and get billed on a schedule, just like a bar tab",
            "See your tab balance at a glance with the new balance pill in the top bar",
            "My Tab page shows your pending charges, tab limit, and remaining balance",
            "Tab History page shows all past charges with itemized details you can expand",
            "Add items to your own tab with the self-service form",
            "Set up a payment method securely through Stripe — your card info never touches our server",
            "Automated billing engine charges tabs on a configurable schedule (daily, weekly, or monthly)",
            "Failed charges automatically retry up to 3 times before locking the tab",
            "Email receipts after every successful charge with an itemized breakdown",
            "Guild Stripe accounts can be connected via Stripe Connect — each guild receives their share of charges directly",
            "Members can pick products when adding to their tab — price and description are filled in automatically",
            "Unified Payments admin — one page for outstanding tabs, charge history, billing settings, and Stripe accounts",
            "All financial records are preserved forever — entries are voided, never deleted",
            "Guild pages — each guild now has its own page with an about section and a list of products",
            "Guild leads can edit their guild's about text and manage their product listings directly from the guild page",
        ],
    },
    {
        "version": "1.2.1",
        "date": "2026-04-01",
        "title": "Mobile Sidebar Fix",
        "changes": [
            "Fixed the sidebar on mobile — it now slides open as a drawer with a dark backdrop you can tap to close",
            "Sidebar starts closed on mobile so you get the full screen for content",
            "Tapping a nav link on mobile automatically closes the sidebar",
        ],
    },
    {
        "version": "1.2.0",
        "date": "2026-03-30",
        "title": "Member Management Redesign",
        "changes": [
            "Admin Members page now lets you create users with a login right from the add form",
            "Added email aliases — members can have multiple email addresses and log in with any of them",
            "New 'Users' filter on the Members page to see who has logged into the app",
            "Search now finds members by their alias emails too",
            "Removed the separate User admin page — everything is managed through Members now",
        ],
    },
    {
        "version": "1.1.2",
        "date": "2026-03-30",
        "title": "Mobile Sidebar Fix",
        "changes": [
            "Fixed the sidebar menu button not working on Android phones — the side menu now opens and closes properly on mobile",
        ],
    },
    {
        "version": "1.1.1",
        "date": "2026-03-28",
        "title": "Better Discord Announcements",
        "changes": [
            "Discord now gets a friendly release announcement when updates go live — with version and what changed",
            "Removed noisy PR-opened notifications so the channel stays clean",
        ],
    },
    {
        "version": "1.1.0",
        "date": "2026-03-28",
        "title": "Vote Standings & Discord Notifications",
        "changes": [
            "Live vote standings with bar charts on the guild voting page — see who's leading in real time",
            "Admin voting dashboard now shows visual bar charts for vote leaders",
            "Discord notifications — the team gets pinged when PRs are opened or code is merged to main",
        ],
    },
    {
        "version": "1.0.3",
        "date": "2026-03-28",
        "title": "Login & Email Fixes",
        "changes": [
            "Members synced from Airtable can now log in immediately — no signup step needed",
            "All emails from Past Lives are now properly branded (no more 'example.com')",
            "Table columns in the admin panel are now left-aligned for easier reading",
        ],
    },
    {
        "version": "1.0.2",
        "date": "2026-03-28",
        "title": "Admin Fixes",
        "changes": [
            "Role management moved out of the member directory — it now lives in the admin panel only",
            "Login code entry allows up to 5 attempts before locking out (was 3)",
        ],
    },
    {
        "version": "1.0.1",
        "date": "2026-03-27",
        "title": "Hotfix",
        "changes": [
            "Guild vote history from before launch is now reflected in voting results",
            "Login code emails no longer show [example.com] in the subject line",
            "Login page email field now shows the correct placeholder",
        ],
    },
    {
        "version": "1.0.0",
        "date": "2026-03-27",
        "title": "Launch Day",
        "changes": [
            "Vote for your favorite guilds each month and see how funding gets split",
            "Your own member hub — one place for voting, directory, and settings",
            "Passwordless sign-in — just enter your email and we send you a code",
            "Member directory — find other members, see their bios and contact info",
            "Member roles — admins, guild officers, and regular members each see what they need",
            "Admins can invite new members, manage the roster, and take funding snapshots",
            "Send us feedback anytime from the Feedback button",
            "Works on your phone — install it like an app from your browser",
            "Forgot which email you signed up with? The new account finder has you covered",
        ],
    },
]
