"""Custom model fields for the billing app.

EncryptedCharField stores symmetric-encrypted strings using Fernet (AES-128-CBC + HMAC).
The encryption key comes from settings.STRIPE_FIELD_ENCRYPTION_KEY — a Fernet key
generated by `Fernet.generate_key()`. Losing the key bricks all stored secrets.
"""

from __future__ import annotations

from typing import Any

from cryptography.fernet import Fernet
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.db import models


def _fernet() -> Fernet:
    """Return a Fernet instance built from settings.STRIPE_FIELD_ENCRYPTION_KEY.

    Raises:
        ImproperlyConfigured: If the key is missing or malformed.
    """
    key = getattr(settings, "STRIPE_FIELD_ENCRYPTION_KEY", "")
    if not key:
        raise ImproperlyConfigured(
            "STRIPE_FIELD_ENCRYPTION_KEY is not set. Generate one with "
            '`python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"` '
            "and set it as an environment variable."
        )
    try:
        return Fernet(key.encode() if isinstance(key, str) else key)
    except (ValueError, TypeError) as exc:
        raise ImproperlyConfigured(f"STRIPE_FIELD_ENCRYPTION_KEY is malformed: {exc}") from exc


class EncryptedCharField(models.CharField):
    """A CharField whose value is symmetrically encrypted at rest.

    Plaintext is exposed as a normal Python string in model instances; the value
    in the database column is the Fernet ciphertext (which is longer than the
    plaintext, so set max_length generously).
    """

    description = "CharField encrypted with Fernet at rest."

    def from_db_value(self, value: Any, expression: Any, connection: Any) -> str | None:
        if value is None or value == "":
            return value
        return _fernet().decrypt(value.encode()).decode()

    def get_prep_value(self, value: Any) -> str | None:
        if value is None or value == "":
            return value
        return _fernet().encrypt(str(value).encode()).decode()
