# Generated by Django 6.0.2 on 2026-03-01 18:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("membership", "0005_guild_cover_image_guild_description_guild_icon_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rentable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rental_period",
                    models.CharField(choices=[("hours", "Hours"), ("days", "Days"), ("weeks", "Weeks")], max_length=20),
                ),
                ("cost_per_period", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revenue_split",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rentables",
                        to="billing.revenuesplit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rentable",
                "verbose_name_plural": "Rentables",
                "ordering": ["tool", "rental_period"],
            },
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checked_out_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("due_at", models.DateTimeField()),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("returned", "Returned"), ("overdue", "Overdue")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rentals",
                        to="billing.order",
                    ),
                ),
                (
                    "rentable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rentals", to="tools.rentable"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rentals", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Rental",
                "verbose_name_plural": "Rentals",
                "ordering": ["-checked_out_at"],
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="tools/")),
                ("estimated_value", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "owner_type",
                    models.CharField(
                        choices=[("guild", "Guild"), ("member", "Member"), ("org", "Organization")],
                        default="org",
                        max_length=20,
                    ),
                ),
                ("owner_id", models.PositiveIntegerField(blank=True, null=True)),
                ("is_reservable", models.BooleanField(default=False)),
                ("is_rentable", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tools",
                        to="membership.guild",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool",
                "verbose_name_plural": "Tools",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="rentable",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="rentables", to="tools.tool"
            ),
        ),
        migrations.CreateModel(
            name="ToolReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed"), ("cancelled", "Cancelled")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reservations", to="tools.tool"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool Reservation",
                "verbose_name_plural": "Tool Reservations",
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="documents/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["content_type", "object_id"], name="tools_docum_content_803d35_idx")],
            },
        ),
    ]
